version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: haven-postgres
    environment:
      POSTGRES_USER: haven
      POSTGRES_PASSWORD: haven
      POSTGRES_DB: haven
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U haven"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Haven service will be added in a later commit
  # haven:
  #   build: .
  #   container_name: haven-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: postgresql+asyncpg://haven:haven@postgres:5432/haven
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres-data: