app:
  name: haven
  version: ${oc.env:APP_VERSION,0.1.0}
  debug: true
  env: local

server:
  host: ${oc.env:APP_HOST,0.0.0.0}
  port: ${oc.env:APP_PORT,8080}
  reload: true

cors:
  allow_origins: 
    - "http://localhost:3000"
    - "http://localhost:5173"  # Vite default
    - "http://localhost:8080"  # API docs
    - "http://app.haven.local:3000"
    - "http://app.haven.local:5173"
    - "http://api.haven.local:8080"
    - "http://haven.local"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]