"""add_slug_to_repositories

Revision ID: c598eca0cf8f
Revises: 0776b841d098
Create Date: 2025-07-17 15:35:11.121850+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c598eca0cf8f'
down_revision: Union[str, None] = '0776b841d098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('slug', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_repositories_slug'), 'repositories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_slug'), table_name='repositories')
    op.drop_column('repositories', 'slug')
    # ### end Alembic commands ###