"""create_users_table

Revision ID: 6059b68de824
Revises: 001_initial
Create Date: 2025-07-16 19:03:07.604910+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6059b68de824"
down_revision: str | None = "001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.alter_column(
        "records",
        "id",
        existing_type=sa.UUID(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_records_created_at"), table_name="records")
    op.drop_index(op.f("ix_records_updated_at"), table_name="records")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_records_updated_at"), "records", ["updated_at"], unique=False)
    op.create_index(op.f("ix_records_created_at"), "records", ["created_at"], unique=False)
    op.alter_column(
        "records",
        "id",
        existing_type=sa.String(length=36),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
