"""add_diff_html_to_commits

Revision ID: 55fa54dcd01a
Revises: b1babe0f8b3b
Create Date: 2025-07-17 02:04:34.088252+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55fa54dcd01a"
down_revision: str | None = "b1babe0f8b3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("commits", sa.Column("diff_html_path", sa.String(length=500), nullable=True))
    op.add_column(
        "commits", sa.Column("diff_generated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commits", "diff_generated_at")
    op.drop_column("commits", "diff_html_path")
    # ### end Alembic commands ###
